# Generated by Django 3.2.7 on 2021-10-30 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('adres', models.CharField(blank=True, max_length=40)),
                ('strona_internetowa', models.URLField(blank=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'salons',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None)),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='core.salon')),
            ],
            options={
                'verbose_name_plural': 'employees',
            },
        ),
    ]
