# Generated by Django 3.2.7 on 2021-10-26 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('adres', models.CharField(blank=True, max_length=40)),
                ('strona_internetowa', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'salons',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('date', models.DateField(verbose_name='Date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='core.employee')),
                ('related_activity', models.ManyToManyField(blank=True, to='core.Visit', verbose_name='Related Visits')),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='core.salon')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='core.salon'),
        ),
    ]
