# Generated by Django 3.2.6 on 2021-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='adres',
            field=models.TextField(blank=True),
        ),
    ]
