# Generated by Django 3.2.6 on 2021-10-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salon_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='core.salon')),
            ],
            options={
                'verbose_name_plural': 'Employes',
            },
        ),
    ]
