# Generated by Django 3.2.6 on 2021-10-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211022_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='email',
        ),
    ]
