# Generated by Django 3.2.6 on 2021-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
