# Generated by Django 3.2.6 on 2021-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='surname',
            field=models.TextField(blank=True),
        ),
    ]
