# Generated by Django 3.2.6 on 2021-10-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_employe_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
