# Generated by Django 3.2.6 on 2021-10-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='surname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
