# Generated by Django 3.2.6 on 2021-10-22 17:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employe_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None),
        ),
    ]
