# Generated by Django 3.2.6 on 2021-10-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employe_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='adres',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
