# Generated by Django 3.2.6 on 2021-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_salon_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='strona_internetowa',
            field=models.URLField(blank=True),
        ),
    ]
