# Generated by Django 3.2.6 on 2021-10-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employe_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='salon',
        ),
    ]
