# Generated by Django 3.2.6 on 2021-10-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_employe_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salon',
            field=models.ForeignKey(default='select', on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='core.salon'),
        ),
    ]
