# Generated by Django 3.2.6 on 2021-10-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_employe_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='core.salon'),
        ),
    ]
