# Generated by Django 3.2.6 on 2021-10-22 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211022_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
