# Generated by Django 3.2.6 on 2021-10-23 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employe_salon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None)),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='core.salon')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
