# Generated by Django 3.2.6 on 2021-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211023_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salon',
        ),
        migrations.AddField(
            model_name='salon',
            name='adres',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salon',
            name='strona_internetowa',
            field=models.URLField(blank=True),
        ),
    ]
